/* A list of file names of package Nix expressions, whose base names
   match the intended attribute names, and that do not need to be
   called with any overrides. Thus, listing ‘./foo.nix’ here is
   equivalent to defining the attribute

     foo = callPackage ./foo.nix { };

   in all-packages.nix. */

[
  applications/audio/a2jmidid
  applications/audio/ams-lv2
  applications/audio/audacious
  applications/audio/bristol
  applications/audio/cantata
  applications/audio/caps
  applications/audio/clementine
  applications/audio/cmus
  applications/audio/csound
  applications/audio/distrho
  applications/audio/drumkv1
  applications/audio/easytag
  applications/audio/ekho
  applications/audio/espeak
  applications/audio/flac
  applications/audio/fldigi
  applications/audio/fluidsynth
  applications/audio/gigedit
  applications/audio/gmpc
  applications/audio/gmu
  applications/audio/google-musicmanager
  applications/audio/gpodder
  applications/audio/hydrogen
  applications/audio/id3v2
  applications/audio/ingen
  applications/audio/jackmeter
  applications/audio/jalv
  applications/audio/lame
  applications/audio/lash
  applications/audio/lastfmsubmitd
  applications/audio/lastwatch
  applications/audio/lmms
  applications/audio/mhwaveedit
  applications/audio/mi2ly
  applications/audio/mid2key
  applications/audio/mikmod
  applications/audio/milkytracker
  applications/audio/minimodem
  applications/audio/moc
  applications/audio/mopidy
  applications/audio/mopidy-spotify
  applications/audio/mp3info
  applications/audio/mp3splt
  applications/audio/mpc123
  applications/audio/mpg123
  applications/audio/mpg321
  applications/audio/ncmpc
  applications/audio/ncmpcpp
  applications/audio/normalize
  applications/audio/opusfile
  applications/audio/pamixer
  applications/audio/pavucontrol
  applications/audio/pianobar
  applications/audio/pianobooster
  applications/audio/picard
  applications/audio/praat
  applications/audio/projectm
  applications/audio/puredata
  applications/audio/qjackctl
  applications/audio/qmmp
  applications/audio/qsampler
  applications/audio/qsynth
  applications/audio/qtractor
  applications/audio/rubyripper
  applications/audio/samplv1
  applications/audio/seq24
  applications/audio/setbfree
  applications/audio/shntool
  applications/audio/snd
  applications/audio/streamripper
  applications/audio/synthv1
  applications/audio/transcode
  applications/audio/vmpk
  applications/audio/xmp
  applications/audio/zynaddsubfx
  applications/display-managers/lightdm
  applications/editors/aewan
  applications/editors/bvi
  applications/editors/codeblocks
  applications/editors/dhex
  applications/editors/ed
  applications/editors/elvis
  applications/editors/flpsed
  applications/editors/geany
  applications/editors/hexedit
  applications/editors/jedit
  applications/editors/joe
  applications/editors/lighttable
  applications/editors/mg
  applications/editors/nano
  applications/editors/netbeans
  applications/editors/nvi
  applications/editors/nvpy
  applications/editors/scite
  applications/editors/sublime
  applications/editors/texmaker
  applications/editors/texstudio
  applications/editors/vbindiff
  applications/editors/vim
  applications/editors/zile
  applications/graphics/alchemy
  applications/graphics/autopanosiftc
  applications/graphics/batik
  applications/graphics/comical
  applications/graphics/djview
  applications/graphics/fbida
  applications/graphics/feh
  applications/graphics/freepv
  applications/graphics/geeqie
  applications/graphics/gocr
  applications/graphics/gpicview
  applications/graphics/gqview
  applications/graphics/grafx2
  applications/graphics/graphicsmagick
  applications/graphics/hugin
  applications/graphics/ipe
  applications/graphics/mcomix
  applications/graphics/meshlab
  applications/graphics/minidjvu
  applications/graphics/mirage
  applications/graphics/mypaint
  applications/graphics/ocrad
  applications/graphics/openimageio
  applications/graphics/openscad
  applications/graphics/panotools
  applications/graphics/paraview
  applications/graphics/pencil
  applications/graphics/photivo
  applications/graphics/potrace
  applications/graphics/pqiv
  applications/graphics/qiv
  applications/graphics/qtpfsgui
  applications/graphics/rapcad
  applications/graphics/shotwell
  applications/graphics/smartdeblur
  applications/graphics/sxiv
  applications/graphics/synfigstudio
  applications/graphics/tesseract
  applications/graphics/ufraw
  applications/graphics/viewnior
  applications/graphics/xara
  applications/graphics/xfig
  applications/graphics/zgrviewer
  applications/ike
  applications/misc/abook
  applications/misc/audio/sox
  applications/misc/audio/soxr
  applications/misc/audio/wavesurfer
  applications/misc/avrdudess
  applications/misc/bibletime
  applications/misc/bitcoin
  applications/misc/calibre
  applications/misc/camlistore
  applications/misc/cdrtools
  applications/misc/cura
  applications/misc/curaengine
  applications/misc/d4x
  applications/misc/djvulibre
  applications/misc/dunst
  applications/misc/eaglemode
  applications/misc/electrum
  applications/misc/epdfview
  applications/misc/evopedia
  applications/misc/evtest
  applications/misc/fbreader
  applications/misc/finalterm
  applications/misc/freicoin
  applications/misc/gammu
  applications/misc/get_iplayer
  applications/misc/gkrellm
  applications/misc/gmrun
  applications/misc/gnuradio-osmosdr
  applications/misc/goldendict
  applications/misc/gphoto2
  applications/misc/gpsbabel
  applications/misc/gpscorrelate
  applications/misc/gqrx
  applications/misc/gv
  applications/misc/jigdo
  applications/misc/keepass
  applications/misc/keepassx
  applications/misc/librecad
  applications/misc/lxappearance
  applications/misc/lyx
  applications/misc/makeself
  applications/misc/merkaartor
  applications/misc/mrxvt
  applications/misc/mupdf
  applications/misc/navipowm
  applications/misc/navit
  applications/misc/nut
  applications/misc/ocropus
  applications/misc/openjump
  applications/misc/pcmanfm
  applications/misc/pgadmin
  applications/misc/pinfo
  applications/misc/posterazor
  applications/misc/printrun
  applications/misc/procmail
  applications/misc/pstree
  applications/misc/qgis
  applications/misc/qtbitcointrader
  applications/misc/ranger
  applications/misc/robomongo
  applications/misc/rtl-sdr
  applications/misc/rxvt
  applications/misc/sbagen
  applications/misc/sdcv
  applications/misc/synergy
  applications/misc/taskjuggler
  applications/misc/taskwarrior
  applications/misc/tint2
  applications/misc/twmn
  applications/misc/urlview
  applications/misc/vanitygen
  applications/misc/vifm
  applications/misc/wmname
  applications/misc/wordnet
  applications/misc/xca
  applications/misc/xchm
  applications/misc/xfontsel
  applications/misc/xmove
  applications/misc/xterm
  applications/misc/yate
  applications/misc/ykpers
  applications/networking/browsers/arora
  applications/networking/browsers/conkeror
  applications/networking/browsers/elinks
  applications/networking/browsers/links
  applications/networking/browsers/links2
  applications/networking/browsers/lynx
  applications/networking/browsers/midori
  applications/networking/browsers/mozilla-plugins/fribid
  applications/networking/browsers/mozilla-plugins/nspluginwrapper
  applications/networking/cluster/hadoop
  applications/networking/cluster/rq
  applications/networking/cluster/spark
  applications/networking/davmail
  applications/networking/dropbox
  applications/networking/dropbox-cli
  applications/networking/esniper
  applications/networking/feedreaders/newsbeuter
  applications/networking/ftp/filezilla
  applications/networking/ids/bro
  applications/networking/ids/daq
  applications/networking/ids/snort
  applications/networking/instant-messengers/amsn
  applications/networking/instant-messengers/centerim
  applications/networking/instant-messengers/fuze
  applications/networking/instant-messengers/gajim
  applications/networking/instant-messengers/gtmess
  applications/networking/instant-messengers/hipchat
  applications/networking/instant-messengers/jitsi
  applications/networking/instant-messengers/mcabber
  applications/networking/instant-messengers/oneteam
  applications/networking/instant-messengers/pidgin-plugins/skype4pidgin
  applications/networking/instant-messengers/tkabber
  applications/networking/instant-messengers/toxic
  applications/networking/instant-messengers/vacuum
  applications/networking/iptraf
  applications/networking/irc/bip
  applications/networking/irc/chatzilla
  applications/networking/irc/hexchat
  applications/networking/irc/ii
  applications/networking/irc/weechat
  applications/networking/irc/xchat
  applications/networking/jmeter
  applications/networking/mailreaders/mailpile
  applications/networking/mailreaders/mutt
  applications/networking/msmtp
  applications/networking/netperf
  applications/networking/newsreaders/liferea
  applications/networking/newsreaders/slrn
  applications/networking/notbit
  applications/networking/offrss
  applications/networking/p2p/freenet
  applications/networking/p2p/ncdc
  applications/networking/p2p/qbittorrent
  applications/networking/p2p/transmission
  applications/networking/p2p/tribler
  applications/networking/p2p/twister
  applications/networking/pjsip
  applications/networking/remote/putty
  applications/networking/remote/rdesktop
  applications/networking/remote/remmina
  applications/networking/remote/ssvnc
  applications/networking/seafile-client
  applications/networking/siproxd
  applications/networking/sniffers/ettercap
  applications/networking/sniffers/kismet
  applications/networking/sniffers/wireshark
  applications/networking/syncthing
  applications/networking/umurmur
  applications/networking/vnstat
  applications/networking/yafc
  applications/networking/znc
  applications/office/antiword
  applications/office/homebank
  applications/office/mmex
  applications/office/zotero
  applications/science/astronomy/gravit
  applications/science/astronomy/stellarium
  applications/science/astronomy/xplanet
  applications/science/biology/emboss
  applications/science/biology/mrbayes
  applications/science/biology/pal2nal
  applications/science/biology/paml
  applications/science/electronics/archimedes
  applications/science/electronics/caneda
  applications/science/electronics/gtkwave
  applications/science/electronics/ngspice
  applications/science/electronics/pulseview
  applications/science/electronics/qfsm
  applications/science/electronics/qucs
  applications/science/electronics/verilog
  applications/science/electronics/xoscope
  applications/science/geometry/tetgen
  applications/science/logic/alt-ergo
  applications/science/logic/cvc3
  applications/science/logic/ekrhyper
  applications/science/logic/hol
  applications/science/logic/iprover
  applications/science/logic/lci
  applications/science/logic/leo2
  applications/science/logic/logisim
  applications/science/logic/ltl2ba
  applications/science/logic/minisat
  applications/science/logic/opensmt
  applications/science/logic/otter
  applications/science/logic/picosat
  applications/science/logic/prover9
  applications/science/logic/satallax
  applications/science/logic/spass
  applications/science/logic/stp
  applications/science/logic/tptp
  applications/science/logic/verifast
  applications/science/logic/why3
  applications/science/logic/yices
  applications/science/logic/z3
  applications/science/math/ecm
  applications/science/math/fricas
  applications/science/math/gap
  applications/science/math/ginac
  applications/science/math/jags
  applications/science/math/mathematica
  applications/science/math/maxima
  applications/science/math/msieve
  applications/science/math/pari
  applications/science/math/sage
  applications/science/math/singular
  applications/science/math/weka
  applications/science/math/wxmaxima
  applications/science/math/yacas
  applications/science/misc/boinc
  applications/science/misc/golly
  applications/science/misc/megam
  applications/science/misc/root
  applications/science/misc/simgrid
  applications/science/misc/tulip
  applications/science/misc/vite
  applications/search/doodle
  applications/search/recoll
  applications/version-management/bazaar
  applications/version-management/cvs
  applications/version-management/cvs2svn
  applications/version-management/cvsps
  applications/version-management/diffuse
  applications/version-management/fossil
  applications/version-management/git-and-tools/cgit
  applications/version-management/gitolite
  applications/version-management/gource
  applications/version-management/guitone
  applications/version-management/mr
  applications/version-management/rapidsvn
  applications/version-management/rcs
  applications/version-management/tkcvs
  applications/version-management/vcprompt
  applications/version-management/vcsh
  applications/version-management/veracity
  applications/video/avidemux
  applications/video/avxsynth
  applications/video/cc1394
  applications/video/cinelerra
  applications/video/dvdauthor
  applications/video/gpac
  applications/video/handbrake
  applications/video/kazam
  applications/video/lxdvdrip
  applications/video/makemkv
  applications/video/mkvtoolnix
  applications/video/mplayer2
  applications/video/mythtv
  applications/video/ogmtools
  applications/video/omxplayer
  applications/video/simplescreenrecorder
  applications/video/smplayer
  applications/video/subtitleeditor
  applications/video/vlc
  applications/video/xawtv
  applications/virtualization/OVMF
  applications/virtualization/bochs
  applications/virtualization/docker
  applications/virtualization/nova
  applications/virtualization/qemu
  applications/virtualization/virtinst
  applications/virtualization/xen
  applications/window-managers/compton
  applications/window-managers/dzen2
  applications/window-managers/fbpanel
  applications/window-managers/fvwm
  applications/window-managers/herbstluftwm
  applications/window-managers/i3
  applications/window-managers/icewm
  applications/window-managers/jwm
  applications/window-managers/larswm
  applications/window-managers/matchbox
  applications/window-managers/openbox
  applications/window-managers/ratpoison
  applications/window-managers/stalonetray
  applications/window-managers/tabbed
  applications/window-managers/trayer
  applications/window-managers/vwm
  applications/window-managers/weston
  applications/window-managers/windowmaker
  applications/window-managers/xcompmgr
  build-support/fetchpatch
  build-support/libredirect
  data/fonts/andagii
  data/fonts/aurulent-sans
  data/fonts/clearlyU
  data/fonts/corefonts
  data/fonts/eb-garamond
  data/fonts/gentium
  data/fonts/inconsolata
  data/fonts/ipafont
  data/fonts/junicode
  data/fonts/kochi-substitute
  data/fonts/kochi-substitute-naga10
  data/fonts/lmodern
  data/fonts/lohit-fonts
  data/fonts/nafees
  data/fonts/oldstandard
  data/fonts/opensans-ttf
  data/fonts/poly
  data/fonts/symbola
  data/fonts/theano
  data/fonts/tipa
  data/fonts/unifont
  data/icons/tango-icon-theme
  data/misc/cacert
  data/misc/freepats
  data/misc/miscfiles
  data/misc/tzdata
  data/sgml+xml/schemas/xml-dtd/xhtml1
  desktops/enlightenment
  development/arduino/ino
  development/compilers/aldor
  development/compilers/aliceml
  development/compilers/aspectj
  development/compilers/ats
  development/compilers/avra
  development/compilers/bigloo
  development/compilers/chicken
  development/compilers/clean
  development/compilers/compcert
  development/compilers/dev86
  development/compilers/dmd
  development/compilers/ecl
  development/compilers/edk2
  development/compilers/eql
  development/compilers/fpc
  development/compilers/fsharp
  development/compilers/gambit
  development/compilers/gprolog
  development/compilers/haxe
  development/compilers/hhvm
  development/compilers/hugs
  development/compilers/iasl
  development/compilers/ikarus
  development/compilers/jikes
  development/compilers/lessc
  development/compilers/mcpp
  development/compilers/mercury
  development/compilers/mlton
  development/compilers/mozart
  development/compilers/nasm
  development/compilers/neko
  development/compilers/orc
  development/compilers/path64
  development/compilers/polyml
  development/compilers/qi
  development/compilers/rdmd
  development/compilers/roadsend
  development/compilers/rust
  development/compilers/sdcc
  development/compilers/stalin
  development/compilers/tinycc
  development/compilers/urweb
  development/compilers/vs90wrapper
  development/compilers/webdsl
  development/compilers/yap
  development/compilers/yasm
  development/eclipse/ecj
  development/guile-modules/guile-xcb
  development/interpreters/angelscript
  development/interpreters/clisp
  development/interpreters/clojure
  development/interpreters/dart
  development/interpreters/elixir
  development/interpreters/groovy
  development/interpreters/io
  development/interpreters/j
  development/interpreters/kona
  development/interpreters/luajit
  development/interpreters/picolisp
  development/interpreters/racket
  development/interpreters/rakudo
  development/interpreters/rascal
  development/interpreters/regina
  development/interpreters/scheme48
  development/interpreters/scsh
  development/interpreters/spidermonkey
  development/interpreters/tcl
  development/libraries/SDL2_gfx
  development/libraries/SDL2_image
  development/libraries/SDL2_mixer
  development/libraries/SDL_gfx
  development/libraries/SDL_mixer
  development/libraries/SDL_net
  development/libraries/SDL_sound
  development/libraries/SDL_ttf
  development/libraries/Xaw3d
  development/libraries/a52dec
  development/libraries/aacskeys
  development/libraries/aalib
  development/libraries/accountsservice
  development/libraries/acl
  development/libraries/adns
  development/libraries/afflib
  development/libraries/agg
  development/libraries/allegro
  development/libraries/amrnb
  development/libraries/amrwb
  development/libraries/apr
  development/libraries/aqbanking
  development/libraries/asio
  development/libraries/aspell
  development/libraries/atk
  development/libraries/attica
  development/libraries/attr
  development/libraries/aubio
  development/libraries/audio/libbs2b
  development/libraries/audio/lilv
  development/libraries/audio/lv2
  development/libraries/audio/lvtk
  development/libraries/audio/raul
  development/libraries/audio/sratom
  development/libraries/audio/suil
  development/libraries/audio/vamp
  development/libraries/axis
  development/libraries/babl
  development/libraries/beecrypt
  development/libraries/boolstuff
  development/libraries/botan
  development/libraries/box2d
  development/libraries/buddy
  development/libraries/bullet
  development/libraries/bwidget
  development/libraries/caelum
  development/libraries/cairomm
  development/libraries/capnproto
  development/libraries/capstone
  development/libraries/ccrtp
  development/libraries/celt
  development/libraries/cfitsio
  development/libraries/cgui
  development/libraries/check
  development/libraries/chmlib
  development/libraries/chromaprint
  development/libraries/cil
  development/libraries/clanlib
  development/libraries/classads
  development/libraries/clearsilver
  development/libraries/cln
  development/libraries/cloog
  development/libraries/clutter
  development/libraries/clutter-gst
  development/libraries/cminpack
  development/libraries/cogl
  development/libraries/coin3d
  development/libraries/commoncpp2
  development/libraries/concurrencykit
  development/libraries/confuse
  development/libraries/coredumper
  development/libraries/cpp-netlib
  development/libraries/cppunit
  development/libraries/cracklib
  development/libraries/ctl
  development/libraries/dbus
  development/libraries/dclib
  development/libraries/despotify
  development/libraries/directfb
  development/libraries/dotconf
  development/libraries/dotnetfx35
  development/libraries/dotnetfx40
  development/libraries/dssi
  development/libraries/dxflib
  development/libraries/eigen
  development/libraries/enchant
  development/libraries/enet
  development/libraries/enginepkcs11
  development/libraries/esdl
  development/libraries/eventlog
  development/libraries/exempi
  development/libraries/exiv2
  development/libraries/expat
  development/libraries/faac
  development/libraries/faad2
  development/libraries/facile
  development/libraries/farsight2
  development/libraries/fcgi
  development/libraries/ffms
  development/libraries/fftw
  development/libraries/flann
  development/libraries/flite
  development/libraries/fmod
  development/libraries/fontconfig
  development/libraries/freealut
  development/libraries/freeimage
  development/libraries/freetds
  development/libraries/freetts
  development/libraries/freetype
  development/libraries/fribidi
  development/libraries/ftgl
  development/libraries/funambol
  development/libraries/gamin
  development/libraries/ganv
  development/libraries/gd
  development/libraries/gdal
  development/libraries/gdbm
  development/libraries/geoclue
  development/libraries/geoip
  development/libraries/geos
  development/libraries/ggz_base_libs
  development/libraries/giblib
  development/libraries/giflib
  development/libraries/glew
  development/libraries/glibmm
  development/libraries/glm
  development/libraries/glog
  development/libraries/gloox
  development/libraries/glpk
  development/libraries/gmime
  development/libraries/gmm
  development/libraries/gnet
  development/libraries/gnu-efi
  development/libraries/goocanvas
  development/libraries/google-gflags
  development/libraries/gperftools
  development/libraries/grantlee
  development/libraries/gsasl
  development/libraries/gsl
  development/libraries/gsm
  development/libraries/gsoap
  development/libraries/gss
  development/libraries/gstreamer/legacy/gnonlin
  development/libraries/gstreamer/legacy/gstreamermm
  development/libraries/gtest
  development/libraries/gtkdatabox
  development/libraries/gtkimageview
  development/libraries/gtkmathview
  development/libraries/gtkspell
  development/libraries/gts
  development/libraries/gwenhywfar
  development/libraries/hamlib
  development/libraries/harfbuzz
  development/libraries/hawknl
  development/libraries/herqq
  development/libraries/hspell
  development/libraries/hunspell
  development/libraries/ibus
  development/libraries/icu
  development/libraries/id3lib
  development/libraries/iksemel
  development/libraries/ilbc
  development/libraries/ilixi
  development/libraries/ilmbase
  development/libraries/imlib2
  development/libraries/incrtcl
  development/libraries/indilib
  development/libraries/iniparser
  development/libraries/isl
  development/libraries/itk
  development/libraries/jama
  development/libraries/jansson
  development/libraries/jasper
  development/libraries/java/geoipjava
  development/libraries/java/hsqldb
  development/libraries/java/httpunit
  development/libraries/java/javasvn
  development/libraries/java/jdom
  development/libraries/java/jflex
  development/libraries/java/junit
  development/libraries/java/junixsocket
  development/libraries/java/jzmq
  development/libraries/java/lucene
  development/libraries/java/mockobjects
  development/libraries/java/saxon
  development/libraries/java/smack
  development/libraries/jbig2dec
  development/libraries/jsoncpp
  development/libraries/judy
  development/libraries/lcms2
  development/libraries/ldns
  development/libraries/lensfun
  development/libraries/lesstif
  development/libraries/leveldb
  development/libraries/levmar
  development/libraries/lib3ds
  development/libraries/libaacs
  development/libraries/libaal
  development/libraries/libarchive
  development/libraries/libass
  development/libraries/libassuan
  development/libraries/libassuan1
  development/libraries/libatomic_ops
  development/libraries/libavc1394
  development/libraries/libbluedevil
  development/libraries/libbluray
  development/libraries/libbsd
  development/libraries/libcaca
  development/libraries/libcanberra
  development/libraries/libcangjie
  development/libraries/libcdaudio
  development/libraries/libcddb
  development/libraries/libcdio
  development/libraries/libcello
  development/libraries/libchop
  development/libraries/libcm
  development/libraries/libconfig
  development/libraries/libcredis
  development/libraries/libctemplate
  development/libraries/libcue
  development/libraries/libdaemon
  development/libraries/libdbi
  development/libraries/libdc1394
  development/libraries/libdc1394avt
  development/libraries/libdevil
  development/libraries/libdiscid
  development/libraries/libdivsufsort
  development/libraries/libdmtx
  development/libraries/libdnet
  development/libraries/libdv
  development/libraries/libdvbpsi
  development/libraries/libdvdcss
  development/libraries/libdvdnav
  development/libraries/libdvdread
  development/libraries/libdwarf
  development/libraries/libdwg
  development/libraries/libe-book
  development/libraries/libeatmydata
  development/libraries/libebml
  development/libraries/libedit
  development/libraries/libee
  development/libraries/libelf
  development/libraries/libestr
  development/libraries/libevent
  development/libraries/libewf
  development/libraries/libexif
  development/libraries/libexttextcat
  development/libraries/libf2c
  development/libraries/libffi
  development/libraries/libfixposix
  development/libraries/libfm
  development/libraries/libftdi
  development/libraries/libgadu
  development/libraries/libgcrypt
  development/libraries/libgdiplus
  development/libraries/libgeotiff
  development/libraries/libgig
  development/libraries/libgnurl
  development/libraries/libgphoto2
  development/libraries/libgsf
  development/libraries/libgtop
  development/libraries/libharu
  development/libraries/libical
  development/libraries/libicns
  development/libraries/libiconv
  development/libraries/libid3tag
  development/libraries/libidn
  development/libraries/libiec61883
  development/libraries/libimobiledevice
  development/libraries/libiptcdata
  development/libraries/libivykis
  development/libraries/libjson
  development/libraries/libkate
  development/libraries/libksba
  development/libraries/liblastfm
  development/libraries/liblastfmSF
  development/libraries/liblo
  development/libraries/liblockfile
  development/libraries/liblogging
  development/libraries/liblscp
  development/libraries/libmad
  development/libraries/libmatchbox
  development/libraries/libmatroska
  development/libraries/libmbim
  development/libraries/libmcrypt
  development/libraries/libmcs
  development/libraries/libmemcached
  development/libraries/libmhash
  development/libraries/libmicrohttpd
  development/libraries/libmilter
  development/libraries/libmkv
  development/libraries/libmms
  development/libraries/libmng
  development/libraries/libmnl
  development/libraries/libmodbus
  development/libraries/libmodplug
  development/libraries/libmowgli
  development/libraries/libmp3splt
  development/libraries/libmpcdec
  development/libraries/libmpeg2
  development/libraries/libmrss
  development/libraries/libmsgpack
  development/libraries/libmsn
  development/libraries/libmspack
  development/libraries/libmtp
  development/libraries/libmusclecard
  development/libraries/libmwaw
  development/libraries/libmx
  development/libraries/libnatspec
  development/libraries/libnet
  development/libraries/libnetfilter_conntrack
  development/libraries/libnetfilter_queue
  development/libraries/libnfnetlink
  development/libraries/libnfsidmap
  development/libraries/libnice
  development/libraries/libnih
  development/libraries/libnotify
  development/libraries/libnova
  development/libraries/libnxml
  development/libraries/liboauth
  development/libraries/libodfgen
  development/libraries/libofa
  development/libraries/libofx
  development/libraries/libogg
  development/libraries/liboggz
  development/libraries/liboil
  development/libraries/liboop
  development/libraries/liboping
  development/libraries/libopus
  development/libraries/libosinfo
  development/libraries/libp11
  development/libraries/libpaper
  development/libraries/libpar2
  development/libraries/libpcap
  development/libraries/libpipeline
  development/libraries/libplist
  development/libraries/libpng
  development/libraries/libpseudo
  development/libraries/libpwquality
  development/libraries/libqalculate
  development/libraries/libqmi
  development/libraries/libraw
  development/libraries/libraw1394
  development/libraries/librdf
  development/libraries/libre
  development/libraries/libresample
  development/libraries/librevenge
  development/libraries/librevisa
  development/libraries/librsync
  development/libraries/libsearpc
  development/libraries/libseccomp
  development/libraries/libsecret
  development/libraries/libserialport
  development/libraries/libsexy
  development/libraries/libshout
  development/libraries/libsigcxx
  development/libraries/libsigsegv
  development/libraries/libsodium
  development/libraries/libsoup
  development/libraries/libspatialindex
  development/libraries/libspatialite
  development/libraries/libspectre
  development/libraries/libssh
  development/libraries/libssh2
  development/libraries/libtasn1
  development/libraries/libtheora
  development/libraries/libtiff
  development/libraries/libtiger
  development/libraries/libtommath
  development/libraries/libtoxcore
  development/libraries/libtsm
  development/libraries/libtunepimp
  development/libraries/libtxc_dxtn
  development/libraries/libtxc_dxtn_s2tc
  development/libraries/libunibreak
  development/libraries/libunistring
  development/libraries/libunwind
  development/libraries/liburcu
  development/libraries/libva
  development/libraries/libvdpau
  development/libraries/libviper
  development/libraries/libvirt
  development/libraries/libvirt-glib
  development/libraries/libvisio
  development/libraries/libvisual
  development/libraries/libvncserver
  development/libraries/libvorbis
  development/libraries/libvpx
  development/libraries/libvterm
  development/libraries/libwacom
  development/libraries/libwebp
  development/libraries/libwmf
  development/libraries/libwpd
  development/libraries/libwpg
  development/libraries/libxkbcommon
  development/libraries/libxklavier
  development/libraries/libxmi
  development/libraries/libxmlxx
  development/libraries/libxmp
  development/libraries/libxslt
  development/libraries/libyaml
  development/libraries/libyubikey
  development/libraries/libzdb
  development/libraries/libzip
  development/libraries/libzrtpcpp
  development/libraries/lightning
  development/libraries/lirc
  development/libraries/log4cplus
  development/libraries/log4cpp
  development/libraries/log4cxx
  development/libraries/loudmouth
  development/libraries/lzo
  development/libraries/martyr
  development/libraries/mdds
  development/libraries/mediastreamer
  development/libraries/menu-cache
  development/libraries/ming
  development/libraries/minixml
  development/libraries/minizip
  development/libraries/minmay
  development/libraries/mlt
  development/libraries/mp4v2
  development/libraries/mpc
  development/libraries/mpich2
  development/libraries/mps
  development/libraries/msilbc
  development/libraries/mtdev
  development/libraries/muparser
  development/libraries/mygui
  development/libraries/mysocketw
  development/libraries/mythes
  development/libraries/nanomsg
  development/libraries/netcdf
  development/libraries/nettle
  development/libraries/newt
  development/libraries/nlopt
  development/libraries/npth
  development/libraries/nspr
  development/libraries/ntrack
  development/libraries/nvidia-texture-tools
  development/libraries/ogre
  development/libraries/ogrepaged
  development/libraries/ois
  development/libraries/oniguruma
  development/libraries/opal
  development/libraries/openal
  development/libraries/openbabel
  development/libraries/opencascade
  development/libraries/opencolorio
  development/libraries/opencsg
  development/libraries/openct
  development/libraries/opencv
  development/libraries/opendbx
  development/libraries/opendkim
  development/libraries/openexr
  development/libraries/openexr_ctl
  development/libraries/openldap
  development/libraries/openmpi
  development/libraries/pango
  development/libraries/pangoxsl
  development/libraries/phonon
  development/libraries/physfs
  development/libraries/pixman
  development/libraries/pkcs11helper
  development/libraries/plib
  development/libraries/pocketsphinx
  development/libraries/podofo
  development/libraries/policykit
  development/libraries/popt
  development/libraries/portmidi
  development/libraries/postgis
  development/libraries/ppl
  development/libraries/prison
  development/libraries/proj
  development/libraries/protobuf
  development/libraries/protobufc
  development/libraries/pth
  development/libraries/ptlib
  development/libraries/qca2
  development/libraries/qhull
  development/libraries/qimageblitz
  development/libraries/qjson
  development/libraries/qoauth
  development/libraries/qrupdate
  development/libraries/qtscriptgenerator
  development/libraries/quesoglc
  development/libraries/qwt
  development/libraries/rabbitmq-c
  development/libraries/re2
  development/libraries/rlog
  development/libraries/ruby_ncursesw_sup
  development/libraries/sbc
  development/libraries/schroedinger
  development/libraries/science/biology/biolib
  development/libraries/science/math/arpack
  development/libraries/science/math/blas
  development/libraries/science/math/liblapack
  development/libraries/science/math/liblbfgs
  development/libraries/science/math/openblas
  development/libraries/scmccid
  development/libraries/serd
  development/libraries/serf
  development/libraries/silgraphite
  development/libraries/simgear
  development/libraries/slang
  development/libraries/smpeg
  development/libraries/snappy
  development/libraries/sodium
  development/libraries/soprano
  development/libraries/soqt
  development/libraries/sord
  development/libraries/spandsp
  development/libraries/sparsehash
  development/libraries/speechd
  development/libraries/speex
  development/libraries/sphinxbase
  development/libraries/srtp
  development/libraries/stlport
  development/libraries/suitesparse
  development/libraries/sword
  development/libraries/szip
  development/libraries/t1lib
  development/libraries/taglib
  development/libraries/talloc
  development/libraries/tbb
  development/libraries/tclap
  development/libraries/tclgpg
  development/libraries/tcllib
  development/libraries/tcltls
  development/libraries/tdb
  development/libraries/tecla
  development/libraries/thrift
  development/libraries/tk
  development/libraries/tnt
  development/libraries/tre
  development/libraries/tremor
  development/libraries/tsocks
  development/libraries/ucl
  development/libraries/ucommon
  development/libraries/unicap
  development/libraries/unixODBC
  development/libraries/urt
  development/libraries/ustr
  development/libraries/vcdimager
  development/libraries/vmime
  development/libraries/vrpn
  development/libraries/vtk
  development/libraries/wayland
  development/libraries/wildmidi
  development/libraries/wtk
  development/libraries/wvstreams
  development/libraries/x264
  development/libraries/xapian
  development/libraries/xbase
  development/libraries/xcb-util-cursor
  development/libraries/xercesc
  development/libraries/xmlsec
  development/libraries/xvidcore
  development/libraries/yajl
  development/libraries/zeitgeist
  development/libraries/zziplib
  development/misc/intelgen4asm
  development/mobile/xcodeenv
  development/mobile/xpwn
  development/python-modules/bsddb3
  development/python-modules/ecdsa
  development/python-modules/mygpoclient
  development/python-modules/numeric
  development/python-modules/psyco
  development/python-modules/pycangjie
  development/python-modules/pycups
  development/python-modules/pyexiv2
  development/python-modules/pygame
  development/python-modules/pylint
  development/python-modules/pyside
  development/python-modules/pyx
  development/python-modules/pyxml
  development/python-modules/rbtools
  development/python-modules/rhpl
  development/python-modules/sip
  development/python-modules/slowaes
  development/tools/analysis/cccc
  development/tools/analysis/checkstyle
  development/tools/analysis/cov-build
  development/tools/analysis/cppcheck
  development/tools/analysis/emma
  development/tools/analysis/findbugs
  development/tools/analysis/jdepend
  development/tools/analysis/lcov
  development/tools/analysis/pmd
  development/tools/analysis/sparse
  development/tools/analysis/spin
  development/tools/analysis/splint
  development/tools/analysis/valkyrie
  development/tools/boomerang
  development/tools/build-managers/bam
  development/tools/build-managers/cmake
  development/tools/build-managers/colormake
  development/tools/build-managers/gradle
  development/tools/build-managers/jam
  development/tools/build-managers/leiningen
  development/tools/build-managers/mk
  development/tools/build-managers/ninja
  development/tools/build-managers/rebar
  development/tools/build-managers/remake
  development/tools/build-managers/scons
  development/tools/casperjs
  development/tools/cdecl
  development/tools/continuous-integration/jenkins
  development/tools/etcdctl
  development/tools/exercism
  development/tools/gnulib
  development/tools/gocode
  development/tools/java/fastjar
  development/tools/java/jclasslib
  development/tools/jq
  development/tools/libsigrok
  development/tools/libsigrokdecode
  development/tools/literate-programming/noweb
  development/tools/misc/arcanist
  development/tools/misc/astyle
  development/tools/misc/autobuild
  development/tools/misc/autoconf
  development/tools/misc/autogen
  development/tools/misc/automoc4
  development/tools/misc/avarice
  development/tools/misc/avrdude
  development/tools/misc/babeltrace
  development/tools/misc/cbrowser
  development/tools/misc/ccache
  development/tools/misc/cflow
  development/tools/misc/cgdb
  development/tools/misc/chrpath
  development/tools/misc/coccinelle
  development/tools/misc/complexity
  development/tools/misc/cppi
  development/tools/misc/cproto
  development/tools/misc/cscope
  development/tools/misc/ctags
  development/tools/misc/dbench
  development/tools/misc/ddd
  development/tools/misc/dejagnu
  development/tools/misc/dfu-programmer
  development/tools/misc/distcc
  development/tools/misc/drush
  development/tools/misc/eggdbus
  development/tools/misc/elfutils
  development/tools/misc/epm
  development/tools/misc/gengetopt
  development/tools/misc/global
  development/tools/misc/gnum4
  development/tools/misc/gob2
  development/tools/misc/gperf
  development/tools/misc/grafana
  development/tools/misc/gtkdialog
  development/tools/misc/indent
  development/tools/misc/intltool
  development/tools/misc/itstool
  development/tools/misc/jscoverage
  development/tools/misc/lsof
  development/tools/misc/ltrace
  development/tools/misc/lttv
  development/tools/misc/ninka
  development/tools/misc/opengrok
  development/tools/misc/openocd
  development/tools/misc/patchelf
  development/tools/misc/pmccabe
  development/tools/misc/prelink
  development/tools/misc/saleae-logic
  development/tools/misc/sloccount
  development/tools/misc/srecord
  development/tools/misc/stlink
  development/tools/misc/stm32flash
  development/tools/misc/strace
  development/tools/misc/swig
  development/tools/misc/sysbench
  development/tools/misc/tcptrack
  development/tools/misc/texi2html
  development/tools/misc/uhd
  development/tools/misc/uisp
  development/tools/misc/uncrustify
  development/tools/misc/unifdef
  development/tools/misc/xc3sprog
  development/tools/misc/yodl
  development/tools/ocaml/omake
  development/tools/packer
  development/tools/parsing/byacc
  development/tools/parsing/jikespg
  development/tools/parsing/peg
  development/tools/parsing/ragel
  development/tools/parsing/re2c
  development/tools/profiling/oprofile
  development/tools/pydb
  development/tools/quilt
  development/tools/sigrok-cli
  development/tools/slimerjs
  development/tools/sqsh
  development/tools/watchman
  development/tools/yuicompressor
  development/web/csslint
  development/web/nodejs
  development/web/remarkjs
  development/web/xmlindent
  games/alienarena
  games/anki
  games/atanks
  games/banner
  games/beret
  games/blackshades
  games/blackshadeselite
  games/blobby
  games/bsdgames
  games/btanks
  games/bzflag
  games/chessdb
  games/crafty
  games/crrcsim
  games/dhewm3
  games/dwarf-therapist
  games/eboard
  games/eduke32
  games/egoboo
  games/exult
  games/flightgear
  games/freeciv
  games/freedink
  games/gav
  games/gemrb
  games/glestae
  games/gltron
  games/gnuchess
  games/gnugo
  games/gsb
  games/gtypist
  games/hexen
  games/icbm3d
  games/keen4
  games/klavaro
  games/kobodeluxe
  games/mars
  games/micropolis
  games/minecraft
  games/minecraft-server
  games/naev
  games/nexuiz
  games/njam
  games/oilrush
  games/openlierox
  games/openra
  games/openspades
  games/opentyrian
  games/openxcom
  games/pingus
  games/pioneers
  games/pong3d
  games/prboom
  games/privateer
  games/quantumminigolf
  games/racer
  games/rili
  games/rogue
  games/sauerbraten
  games/scid
  games/scorched3d
  games/scummvm
  games/sdlmame
  games/simutrans
  games/soi
  games/spring
  games/stardust
  games/stepmania
  games/stuntrally
  games/teetertorture
  games/teeworlds
  games/tennix
  games/tibia
  games/tintin
  games/tremulous
  games/trigger
  games/typespeed
  games/ufoai
  games/ultimatestunts
  games/unvanquished
  games/uqm
  games/urbanterror
  games/ut2004demo
  games/vdrift
  games/vectoroids
  games/warmux
  games/warzone2100
  games/worldofgoo
  games/xboard
  games/xconq
  games/xonotic
  games/zdoom
  games/zod
  games/zoom
  misc/beep
  misc/cups/drivers/splix
  misc/drivers/foo2zjs
  misc/drivers/gutenprint
  misc/drivers/hplip
  misc/drivers/xboxdrv
  misc/emulators/VisualBoyAdvance
  misc/emulators/atari800
  misc/emulators/bsod
  misc/emulators/darcnes
  misc/emulators/dlx
  misc/emulators/dosbox
  misc/emulators/fakenes
  misc/emulators/fceux
  misc/emulators/hatari
  misc/emulators/mednafen
  misc/emulators/mupen64plus
  misc/emulators/retroarch
  misc/emulators/uae
  misc/emulators/wxmupen64plus
  misc/foldingathome
  misc/freestyle
  misc/gxemul
  misc/jackaudio
  misc/screensavers/electricsheep
  misc/screensavers/slock
  misc/screensavers/vlock
  misc/screensavers/xautolock
  misc/screensavers/xlockmore
  misc/seafile-shared
  misc/themes/gtk2/gtk-engine-murrine
  misc/themes/mate-icon-theme
  misc/themes/mate-themes
  misc/xosd
  os-specific/darwin/install_name_tool
  os-specific/darwin/otool
  os-specific/darwin/setfile
  os-specific/linux/acpi
  os-specific/linux/acpid
  os-specific/linux/acpitool
  os-specific/linux/afuse
  os-specific/linux/alienfx
  os-specific/linux/atop
  os-specific/linux/audit
  os-specific/linux/busybox
  os-specific/linux/can-utils
  os-specific/linux/checkpolicy
  os-specific/linux/checksec
  os-specific/linux/conspy
  os-specific/linux/cpufrequtils
  os-specific/linux/cramfsswap
  os-specific/linux/criu
  os-specific/linux/cryopid
  os-specific/linux/cryptsetup
  os-specific/linux/dietlibc
  os-specific/linux/dmidecode
  os-specific/linux/dmraid
  os-specific/linux/dmtcp
  os-specific/linux/drbd
  os-specific/linux/e3cfsprogs
  os-specific/linux/ebtables
  os-specific/linux/fbterm
  os-specific/linux/ffado
  os-specific/linux/forktty
  os-specific/linux/fuse
  os-specific/linux/fxload
  os-specific/linux/gfxtablet
  os-specific/linux/gogoclient
  os-specific/linux/guvcview
  os-specific/linux/hdparm
  os-specific/linux/hibernate
  os-specific/linux/hostapd
  os-specific/linux/hwdata
  os-specific/linux/i7z
  os-specific/linux/i810switch
  os-specific/linux/ifenslave
  os-specific/linux/ifplugd
  os-specific/linux/iomelt
  os-specific/linux/iotop
  os-specific/linux/iproute
  os-specific/linux/iptables
  os-specific/linux/iw
  os-specific/linux/jujuutils
  os-specific/linux/kbd
  os-specific/linux/kexectools
  os-specific/linux/keyutils
  os-specific/linux/kmod
  os-specific/linux/kmod-blacklist-ubuntu
  os-specific/linux/kmscon
  os-specific/linux/latencytop
  os-specific/linux/ldm
  os-specific/linux/libaio
  os-specific/linux/libatasmart
  os-specific/linux/libcap
  os-specific/linux/libcgroup
  os-specific/linux/libnl
  os-specific/linux/libnscd
  os-specific/linux/libselinux
  os-specific/linux/libsemanage
  os-specific/linux/libsepol
  os-specific/linux/libsmbios
  os-specific/linux/libvolume_id
  os-specific/linux/lockdep
  os-specific/linux/lsiutil
  os-specific/linux/lsscsi
  os-specific/linux/lvm2
  os-specific/linux/lxc
  os-specific/linux/mcelog
  os-specific/linux/mdadm
  os-specific/linux/mingetty
  os-specific/linux/musl
  os-specific/linux/nss_ldap
  os-specific/linux/numactl
  os-specific/linux/otpw
  os-specific/linux/pam
  os-specific/linux/pam_ccreds
  os-specific/linux/pam_devperm
  os-specific/linux/pam_krb5
  os-specific/linux/pam_ldap
  os-specific/linux/pam_login
  os-specific/linux/pam_ssh_agent_auth
  os-specific/linux/pam_usb
  os-specific/linux/pax-utils
  os-specific/linux/paxctl
  os-specific/linux/pmount
  os-specific/linux/pmtools
  os-specific/linux/policycoreutils
  os-specific/linux/powertop
  os-specific/linux/procps-ng
  os-specific/linux/psmisc
  os-specific/linux/radeontools
  os-specific/linux/regionset
  os-specific/linux/reptyr
  os-specific/linux/rfkill
  os-specific/linux/rtkit
  os-specific/linux/sdparm
  os-specific/linux/sepolgen
  os-specific/linux/setools
  os-specific/linux/shadow
  os-specific/linux/sysfsutils
  os-specific/linux/sysklogd
  os-specific/linux/syslinux
  os-specific/linux/sysstat
  os-specific/linux/sysvinit
  os-specific/linux/ttysnoop
  os-specific/linux/tunctl
  os-specific/linux/uclibc
  os-specific/linux/untie
  os-specific/linux/upower
  os-specific/linux/upstart
  os-specific/linux/usbutils
  os-specific/linux/usermount
  os-specific/linux/wpa_supplicant
  os-specific/linux/wvdial
  os-specific/linux/x86info
  servers/amqp/qpid-cpp
  servers/apcupsd
  servers/beanstalkd
  servers/bird
  servers/computing/storm
  servers/dico
  servers/diod
  servers/dns/bind
  servers/dns/nsd
  servers/elasticmq
  servers/etcd
  servers/fcgiwrap
  servers/felix
  servers/fleet
  servers/ftp/vsftpd
  servers/gpm
  servers/gpsd
  servers/http/apache-modules/mod_evasive
  servers/http/apache-modules/mod_fastcgi
  servers/http/apache-modules/mod_python
  servers/http/apache-modules/mod_wsgi
  servers/http/jboss
  servers/http/jetty
  servers/http/joseki
  servers/http/lighttpd
  servers/http/myserver
  servers/http/nix-binary-cache
  servers/http/redstore
  servers/http/thttpd
  servers/http/tomcat/axis2
  servers/http/winstone
  servers/http/yaws
  servers/icecast
  servers/identd/oidentd
  servers/irc/ngircd
  servers/kippo
  servers/mail/freepops
  servers/mail/mailman
  servers/mail/opensmtpd
  servers/mail/petidomo
  servers/mail/popa3d
  servers/mail/postfix
  servers/mediatomb
  servers/memcached
  servers/monitoring/munin
  servers/monitoring/nagios
  servers/monitoring/seyren
  servers/news/leafnode
  servers/nosql/influxdb
  servers/nosql/mongodb
  servers/nosql/rethinkdb
  servers/nsq
  servers/pies
  servers/polipo
  servers/portmap
  servers/prayer
  servers/radius
  servers/restund
  servers/rippled
  servers/rpcbind
  servers/sabnzbd
  servers/samba
  servers/search/elasticsearch
  servers/search/solr
  servers/serfdom
  servers/shellinabox
  servers/shishi
  servers/sip/freeswitch
  servers/sip/sipwitch
  servers/sql/mariadb
  servers/sql/postgresql/psqlodbc
  servers/unfs3
  servers/varnish
  servers/xinetd
  servers/xmpp/openfire
  shells/dash
  shells/rush
  shells/tcsh
  shells/zsh
  tools/X11/arandr
  tools/X11/bgs
  tools/X11/bumblebee
  tools/X11/hsetroot
  tools/X11/keynav
  tools/X11/nitrogen
  tools/X11/vdpauinfo
  tools/X11/virtualgl
  tools/X11/winswitch
  tools/X11/wmctrl
  tools/X11/x11vnc
  tools/X11/x2vnc
  tools/X11/x2x
  tools/X11/xbindkeys
  tools/X11/xcalib
  tools/X11/xcape
  tools/X11/xchainkeys
  tools/X11/xdg-user-dirs
  tools/X11/xdotool
  tools/X11/xlaunch
  tools/X11/xmacro
  tools/X11/xpra
  tools/X11/xrestop
  tools/X11/xtrace
  tools/admin/analog
  tools/admin/awscli
  tools/admin/sec
  tools/archivers/atool
  tools/archivers/cabextract
  tools/archivers/cpio
  tools/archivers/cromfs
  tools/archivers/dar
  tools/archivers/gnutar
  tools/archivers/p7zip
  tools/archivers/sharutils
  tools/archivers/unarj
  tools/archivers/unrar
  tools/archivers/unshield
  tools/archivers/unzip
  tools/archivers/xarchive
  tools/archivers/xarchiver
  tools/archivers/zip
  tools/archivers/zpaq
  tools/audio/gvolicon
  tools/audio/mpdcron
  tools/backup/bacula
  tools/backup/btar
  tools/backup/chunksync
  tools/backup/duply
  tools/backup/httrack
  tools/backup/obnam
  tools/backup/ori
  tools/backup/partclone
  tools/backup/partimage
  tools/backup/tarsnap
  tools/bluetooth/obexd
  tools/bluetooth/obexfs
  tools/bluetooth/obexftp
  tools/bluetooth/openobex
  tools/cd-dvd/bchunk
  tools/cd-dvd/cdrdao
  tools/cd-dvd/cdrkit
  tools/cd-dvd/cuetools
  tools/cd-dvd/mkcue
  tools/cd-dvd/unetbootin
  tools/cd-dvd/vobcopy
  tools/cd-dvd/vobsub2srt
  tools/cd-dvd/xorriso
  tools/compression/bsdiff
  tools/compression/bzip2
  tools/compression/gzip
  tools/compression/gzrt
  tools/compression/lrzip
  tools/compression/lzip
  tools/compression/lzop
  tools/compression/ncompress
  tools/compression/pbzip2
  tools/compression/pigz
  tools/compression/rzip
  tools/compression/upx
  tools/compression/xdelta
  tools/compression/xz
  tools/compression/zdelta
  tools/compression/zsync
  tools/filesystems/aefs
  tools/filesystems/archivemount
  tools/filesystems/bcache-tools
  tools/filesystems/ceph
  tools/filesystems/chunkfs
  tools/filesystems/ciopfs
  tools/filesystems/curlftpfs
  tools/filesystems/davfs2
  tools/filesystems/dosfstools
  tools/filesystems/e2fsprogs
  tools/filesystems/encfs
  tools/filesystems/extundelete
  tools/filesystems/f2fs-tools
  tools/filesystems/fsfs
  tools/filesystems/fusesmb
  tools/filesystems/genext2fs
  tools/filesystems/glusterfs
  tools/filesystems/jfsutils
  tools/filesystems/jmtpfs
  tools/filesystems/mtdutils
  tools/filesystems/mtools
  tools/filesystems/mtpfs
  tools/filesystems/netatalk
  tools/filesystems/reiser4progs
  tools/filesystems/reiserfsprogs
  tools/filesystems/s3backer
  tools/filesystems/smbnetfs
  tools/filesystems/svnfs
  tools/filesystems/udftools
  tools/filesystems/wdfs
  tools/filesystems/xfsprogs
  tools/filesystems/xtreemfs
  tools/filesystems/yandex-disk
  tools/graphics/argyllcms
  tools/graphics/barcode
  tools/graphics/briss
  tools/graphics/dcraw
  tools/graphics/ditaa
  tools/graphics/exif
  tools/graphics/exiftags
  tools/graphics/gifsicle
  tools/graphics/glxinfo
  tools/graphics/graphviz
  tools/graphics/icoutils
  tools/graphics/jbig2enc
  tools/graphics/jhead
  tools/graphics/logstalgia
  tools/graphics/lprof
  tools/graphics/mscgen
  tools/graphics/netpbm
  tools/graphics/nifskope
  tools/graphics/panomatic
  tools/graphics/pdfread
  tools/graphics/pfstools
  tools/graphics/plotutils
  tools/graphics/pngcrush
  tools/graphics/pngnq
  tools/graphics/pngquant
  tools/graphics/povray
  tools/graphics/pstoedit
  tools/graphics/qrencode
  tools/graphics/scrot
  tools/graphics/welkin
  tools/graphics/wkhtmltopdf
  tools/inputmethods/fcitx
  tools/misc/aescrypt
  tools/misc/apparix
  tools/misc/appdata-tools
  tools/misc/apt-offline
  tools/misc/arp-scan
  tools/misc/autojump
  tools/misc/bc
  tools/misc/bfr
  tools/misc/bmon
  tools/misc/bogofilter
  tools/misc/byobu
  tools/misc/colord
  tools/misc/colord-gtk
  tools/misc/convmv
  tools/misc/cowsay
  tools/misc/cpuminer
  tools/misc/cunit
  tools/misc/cv
  tools/misc/dbacl
  tools/misc/debootstrap
  tools/misc/detox
  tools/misc/direnv
  tools/misc/disper
  tools/misc/dmg2img
  tools/misc/dtach
  tools/misc/dvtm
  tools/misc/ethtool
  tools/misc/expect
  tools/misc/fdupes
  tools/misc/figlet
  tools/misc/file
  tools/misc/fileschanged
  tools/misc/findutils
  tools/misc/fortune
  tools/misc/g500-control
  tools/misc/getopt
  tools/misc/gnuvd
  tools/misc/goaccess
  tools/misc/gparted
  tools/misc/grc
  tools/misc/gummiboot
  tools/misc/hddtemp
  tools/misc/heimdall
  tools/misc/i3minator
  tools/misc/idutils
  tools/misc/ised
  tools/misc/jdiskreport
  tools/misc/kermit
  tools/misc/keychain
  tools/misc/lbdb
  tools/misc/ldapvi
  tools/misc/less
  tools/misc/logstash
  tools/misc/logstash-forwarder
  tools/misc/man
  tools/misc/mc
  tools/misc/mcrl
  tools/misc/mcrl2
  tools/misc/mcrypt
  tools/misc/mdbtools
  tools/misc/megacli
  tools/misc/memtest86
  tools/misc/minicom
  tools/misc/mktorrent
  tools/misc/mmv
  tools/misc/most
  tools/misc/mssys
  tools/misc/multitail
  tools/misc/mysql2pgsql
  tools/misc/ncdu
  tools/misc/ngrok
  tools/misc/pal
  tools/misc/parallel
  tools/misc/parcellite
  tools/misc/pastebinit
  tools/misc/pg_top
  tools/misc/picocom
  tools/misc/pk2cmd
  tools/misc/plantuml
  tools/misc/plowshare
  tools/misc/ponysay
  tools/misc/proxytunnel
  tools/misc/pv
  tools/misc/qjoypad
  tools/misc/recutils
  tools/misc/remind
  tools/misc/renameutils
  tools/misc/rkflashtool
  tools/misc/rlwrap
  tools/misc/rmlint
  tools/misc/rrdtool
  tools/misc/screen
  tools/misc/screenfetch
  tools/misc/shebangfix
  tools/misc/sl
  tools/misc/slsnif
  tools/misc/smc
  tools/misc/stow
  tools/misc/t1utils
  tools/misc/testdisk
  tools/misc/time
  tools/misc/timidity
  tools/misc/tmpwatch
  tools/misc/tmux
  tools/misc/ttf2pt1
  tools/misc/ttmkfdir
  tools/misc/txt2man
  tools/misc/unclutter
  tools/misc/units
  tools/misc/usbmuxd
  tools/misc/uucp
  tools/misc/vfdecrypt
  tools/misc/vorbisgain
  tools/misc/wv
  tools/misc/wv2
  tools/misc/xclip
  tools/misc/xdaliclock
  tools/misc/xmltv
  tools/misc/xsel
  tools/misc/yad
  tools/networking/ahcpd
  tools/networking/altermime
  tools/networking/aria2
  tools/networking/atftp
  tools/networking/autossh
  tools/networking/axel
  tools/networking/babeld
  tools/networking/badvpn
  tools/networking/biosdevname
  tools/networking/bully
  tools/networking/ccnet
  tools/networking/chrony
  tools/networking/cjdns
  tools/networking/cksfv
  tools/networking/cntlm
  tools/networking/connect
  tools/networking/connman
  tools/networking/connmanui
  tools/networking/cutter
  tools/networking/ddclient
  tools/networking/dhcp
  tools/networking/dhcpcd
  tools/networking/dnsmasq
  tools/networking/dnstop
  tools/networking/dropbear
  tools/networking/easyrsa
  tools/networking/eggdrop
  tools/networking/fdm
  tools/networking/filegive
  tools/networking/flvstreamer
  tools/networking/fping
  tools/networking/getmail
  tools/networking/gftp
  tools/networking/gmvault
  tools/networking/haproxy
  tools/networking/host
  tools/networking/hping
  tools/networking/httpie
  tools/networking/hyenae
  tools/networking/iftop
  tools/networking/imapproxy
  tools/networking/inadyn
  tools/networking/inetutils
  tools/networking/iodine
  tools/networking/iperf
  tools/networking/isync
  tools/networking/jnettop
  tools/networking/jwhois
  tools/networking/lftp
  tools/networking/maildrop
  tools/networking/megatools
  tools/networking/miniupnpc
  tools/networking/miniupnpd
  tools/networking/modemmanager
  tools/networking/mpack
  tools/networking/mtr
  tools/networking/nbd
  tools/networking/nc6
  tools/networking/ncat
  tools/networking/ncftp
  tools/networking/ndisc6
  tools/networking/ndjbdns
  tools/networking/netboot
  tools/networking/netcat
  tools/networking/netcat-openbsd
  tools/networking/nethogs
  tools/networking/netrw
  tools/networking/netselect
  tools/networking/ngrep
  tools/networking/ntop
  tools/networking/ntopng
  tools/networking/ntp
  tools/networking/nylon
  tools/networking/nzbget
  tools/networking/openresolv
  tools/networking/openvpn
  tools/networking/oslrd
  tools/networking/p2p/amule
  tools/networking/p2p/azureus
  tools/networking/p2p/libtorrent
  tools/networking/p2p/rtorrent
  tools/networking/par2cmdline
  tools/networking/pdnsd
  tools/networking/philter
  tools/networking/ppp
  tools/networking/pptp
  tools/networking/privoxy
  tools/networking/proxychains
  tools/networking/pwnat
  tools/networking/radvd
  tools/networking/ripmime
  tools/networking/s3cmd
  tools/networking/samplicator
  tools/networking/siege
  tools/networking/sitecopy
  tools/networking/socat
  tools/networking/spiped
  tools/networking/stun
  tools/networking/stunnel
  tools/networking/surfraw
  tools/networking/tcpdump
  tools/networking/tcpflow
  tools/networking/telnet
  tools/networking/tinc
  tools/networking/trickle
  tools/networking/udptunnel
  tools/networking/unbound
  tools/networking/uwimap
  tools/networking/vde2
  tools/networking/vlan
  tools/networking/vpnc
  tools/networking/vtun
  tools/networking/wakelan
  tools/networking/wavemon
  tools/networking/wbox
  tools/networking/webalizer
  tools/networking/weighttp
  tools/networking/wicd
  tools/package-management/checkinstall
  tools/package-management/disnix
  tools/package-management/disnix/DisnixWebService
  tools/package-management/disnix/disnixos
  tools/package-management/dpkg
  tools/package-management/guix
  tools/package-management/nix-prefetch-scripts
  tools/package-management/nix-repl
  tools/package-management/nixops
  tools/package-management/opkg
  tools/package-management/rpm
  tools/security/aespipe
  tools/security/apg
  tools/security/ccid
  tools/security/ccrypt
  tools/security/chkrootkit
  tools/security/clamav
  tools/security/dirmngr
  tools/security/duo-unix
  tools/security/ecryptfs
  tools/security/fail2ban
  tools/security/fprot
  tools/security/gnupg1compat
  tools/security/hashcat
  tools/security/haveged
  tools/security/meo
  tools/security/mkpasswd
  tools/security/mktemp
  tools/security/munge
  tools/security/muscleframework
  tools/security/muscletool
  tools/security/nmap
  tools/security/opensc
  tools/security/ossec
  tools/security/p0f
  tools/security/pcsclite
  tools/security/pinentry
  tools/security/pius
  tools/security/pwgen
  tools/security/scrypt
  tools/security/seccure
  tools/security/ssdeep
  tools/security/sshuttle
  tools/security/ssss
  tools/security/steghide
  tools/security/sudo
  tools/security/super
  tools/security/tcpcrypt
  tools/security/tor
  tools/security/torbutton
  tools/security/vidalia
  tools/security/volatility
  tools/system/acct
  tools/system/ansible
  tools/system/at
  tools/system/bootchart
  tools/system/collectd
  tools/system/cron
  tools/system/dd_rescue
  tools/system/ddrescue
  tools/system/efibootmgr
  tools/system/efivar
  tools/system/fakechroot
  tools/system/fakeroot
  tools/system/fcron
  tools/system/fio
  tools/system/freeipmi
  tools/system/gdmap
  tools/system/gptfdisk
  tools/system/gt5
  tools/system/hardlink
  tools/system/idle3tools
  tools/system/ioping
  tools/system/ipmiutil
  tools/system/logrotate
  tools/system/lshw
  tools/system/monit
  tools/system/pciutils
  tools/system/plan9port
  tools/system/rsyslog
  tools/system/safecopy
  tools/system/sg3_utils
  tools/system/sleuthkit
  tools/system/smartmontools
  tools/system/storebrowse
  tools/system/symlinks
  tools/system/thinkfan
  tools/system/tm
  tools/system/ts
  tools/system/uptimed
  tools/system/vboot_reference
  tools/system/which
  tools/text/ascii
  tools/text/catdoc
  tools/text/colordiff
  tools/text/convertlit
  tools/text/diffstat
  tools/text/diffutils
  tools/text/dos2unix
  tools/text/enca
  tools/text/gawk
  tools/text/gnupatch
  tools/text/gnused
  tools/text/kakasi
  tools/text/mairix
  tools/text/mpage
  tools/text/namazu
  tools/text/numdiff
  tools/text/odt2txt
  tools/text/patchutils
  tools/text/podiff
  tools/text/poedit
  tools/text/qshowdiff
  tools/text/recode
  tools/text/replace
  tools/text/sgml/opensp
  tools/text/silver-searcher
  tools/text/uni2ascii
  tools/text/unoconv
  tools/text/wdiff
  tools/text/wgetpaste
  tools/text/xml/basex
  tools/text/xml/html-xml-utils
  tools/text/xml/jing
  tools/text/xml/rxp
  tools/text/xml/sablotron
  tools/text/xml/trang
  tools/text/xml/xmlstarlet
  tools/typesetting/djvu2pdf
  tools/typesetting/fop
  tools/typesetting/halibut
  tools/typesetting/hevea
  tools/typesetting/lout
  tools/typesetting/pdf2djvu
  tools/typesetting/pdfjam
  tools/typesetting/pdftk
  tools/typesetting/rubber
  tools/typesetting/tex/auctex
  tools/typesetting/tex/lazylist
  tools/typesetting/tex/lkproof
  tools/typesetting/tex/pgfplots
  tools/typesetting/tex/polytable
  tools/typesetting/tex/tex4ht
  tools/typesetting/xmlto
  tools/video/dvgrab
  tools/video/flvtool2
  tools/video/mjpegtools
  tools/video/rtmpdump
  tools/video/swfmill
  tools/video/swftools
  tools/video/vnc2flv
  tools/virtualization/aws
]
